# clusters/mycluster/patches/compliance-patch.yaml
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: compliance-operator
spec:
  subscription:
    channel: stable  # This overrides the "CHANNEL" placeholder in base