apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: compliance-operator
  namespace: open-cluster-management-policies
spec:
  subscription:
    channel: stable
    startingCSV: compliance-operator.v1.8.2
  versions:
    - compliance-operator.v1.8.2