apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-operator
  namespace: openshift-gitops
spec:
  project: cluster-config
  source:
    repoURL: https://github.com/mmwillingham/gitops-standards-repo
    targetRevision: HEAD
    path: clusters/cluster-pq7kv/compliance-operator # Points to local overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management-policies
  syncPolicy:
    automated: { prune: true, selfHeal: true }