apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: enforce-console-plugins
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.openshift.io/v1
        kind: Console
        metadata:
          name: cluster
        spec:
          plugins:
            - openshift-gitops-plugin
            - monitoring-plugin
            - networking-console-plugin