apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: compliance-operator
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  subscription:
    channel: CHANNEL # This is the placeholder we will patch
    name: compliance-operator
    namespace: openshift-compliance
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: compliance-operator.v1.8.2
  versions:
    - compliance-operator.v1.8.2