apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-virtualization-operator
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  operatorGroup:
    name: openshift-virtualization-og
    namespace: openshift-cnv
    targetNamespaces:
      - openshift-cnv
  subscription:
    channel: stable
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: PATCHME
  versions:
    - PATCHME