apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  project: default
  source:
    repoURL: https://github.com/mmwillingham/gitops-standards-repo
    targetRevision: HEAD
    path: clusters/cluster-8qp82/patches/compliance-operator # Points to local overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management-policies
  syncPolicy:
    automated: { prune: true, selfHeal: true }