apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  project: cluster-config
  source:
    repoURL: https://github.com/mmwillingham/gitops-standards-repo
    targetRevision: HEAD
    path: components/external-secrets-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated: { prune: true, selfHeal: true }