apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: node-health-check-operator
  namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: hub
  source:
    path: components/node-health-check-operator
    repoURL: https://github.com/mmwillingham/gitops-standards-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true