apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-maintenance-operator
  namespace: open-cluster-management-policies
  annotations:
    argocd.argoproj.io/sync-wave: "5" # This should be created after the operator group
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  subscription:
    channel: stable
    name: node-maintenance-operator
    namespace: openshift-workload-availability
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: PATCHME
  versions:
    - PATCHME