apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-workload-availability
spec:
  remediationAction: enforce
  complianceType: musthave
  operatorGroup:
    name: shared-workload-availability
    namespace: openshift-workload-availability
    targetNamespaces:
      - openshift-workload-availability